#!/usr/bin/env bash
#a Bash script that install nginx on ubuntu machine
sudo apt-get update
sudo apt-get install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
