#!/usr/bin/env bash
#a Bash script that install nginx on ubuntu machine
#then Configure your Nginx server so that /redirect_me is redirecting to another page.
#then add a 404 page displayed when arequest for unfound website in server
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" > /var/www/html/404.html
sudo sed -i '25i\       error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '26i\        server_name 438412-web-01;' /etc/nginx/sites-available/default
sudo sed -i '27i\        add_header X-Served-By $server_name always;' /etc/nginx/sites-available/default
sudo service nginx restart
